services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mpq
      POSTGRES_PASSWORD: mpq_dev
      POSTGRES_DB: movie_queue
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
